name: gyunny-action

permissions:
  checks: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

env:
  S3_BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # application.properties 추가정보 입력 시작
      - name: Create ./src/main/resources/
        run: |
          mkdir -p  ./src/main/resources/
          
      - name: Add Application Property
        run: |
          echo $JWT_PROPERTIES | ./src/main/resources/application-jwt.properties
        env:
          JWT_PROPERTIES: ${{secrets.JWT_PROPERTIES}}
      - name: Add Application Property
        run: |
          echo $MYSQLDB_PROPERTIES | base64 --decode > ./src/main/resources/application-mysqlDB.properties
        env:
          MYSQLDB_PROPERTIES: ${{secrets.MYSQLDB_PROPERTIES}}
          
      - name: Add Application Property
        run: |
          echo $S3BUCKET_PROPERTIES | base64 --decode > ./src/main/resources/application-S3bucket.properties
        env:
          S3BUCKET_PROPERTIES: ${{secrets.S3BUCKET_PROPERTIES}}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      # 새로 추가 된 부분
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{secrets.AWS_S3_BUCKET_NAME}}/$GITHUB_SHA.zip
      # 새로 추가 된 부분
      - name: Code Deploy
        run: aws deploy create-deployment --application-name springboot-intro --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name cicd-havit --s3-location bucket=${{secrets.AWS_S3_BUCKET_NAME}},bundleType=zip,key=$GITHUB_SHA.zip



